name: crazy_eights_web_client
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+22
  archive: ^2.0.10
  http: ^0.12.0
  web_socket_channel: ^1.0.14

  crazy_eights_common:
    path: ../common

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  image: ^2.1.4
  pedantic: ^1.7.0
  sass_builder: ^2.1.3
  test: ^1.6.0
