name: crazy_eights_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.0
  path: ^1.6.2
  shelf: ^0.7.2
  shelf_static: ^0.2.8
  # shelf_web_socket: ^0.2.3 # it doesn't do what I want :'(
  web_socket_channel: ^1.0.14

  crazy_eights_common:
    path: ../common

dev_dependencies:
  pedantic: ^1.7.0
