name: crazy_eights_common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  built_value: ^6.7.0

dev_dependencies:
  build_runner: ^1.6.1
  built_value_generator: ^6.7.0
  pedantic: ^1.7.0
  test: ^1.6.0
